services:
  cybercygan-api:
    image: ghcr.io/cybercygan/cybercygan-api:latest
    restart: always
    container_name: cybercygan-api
    environment:
      - API_URL=https://api.185.167.99.145.sslip.io/
      - API_NAME=cybercygan-instance
      - REDIS_HOST=cybercygan-redis
    depends_on:
      - cybercygan-redis

  cybercygan-web:
    image: ghcr.io/cybercygan/cybercygan-web:latest
    restart: always
    container_name: cybercygan-web
    environment:
      - API_URL=https://api.185.167.99.145.sslip.io/

  cybercygan-redis:
    image: redis:alpine
    restart: always
    container_name: cybercygan-redis

  caddy:
    image: caddy:latest
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - cybercygan-api
      - cybercygan-web

volumes:
  caddy_data:
  caddy_config:
